### ISSUE TITLE
Loading Error for "converter_and_duration.pkl"

### ISSUE THREAD

**Issue by MCLYang** [shunithaviv/bebopnet-code#4]
I am trying to generate Music and following the Step2. When I run the 
`python jazz_rnn/B_next_note_prediction/generate_from_xml.py`
here is error I got
`Traceback (most recent call last):
  File "jazz_rnn/B_next_note_prediction/generate_from_xml.py", line 322, in <module>
    generate_from_xml(sys.argv[1:])
  File "jazz_rnn/B_next_note_prediction/generate_from_xml.py", line 118, in generate_from_xml
    converter = pickle.load(input_file)
  File "/opt/conda/lib/python3.7/site-packages/bidict/_base.py", line 166, in __setstate__
    setattr(self, slot, value)
AttributeError: 'bidict' object has no attribute 'isinv'
`
Besides, I take model_dir="training_results/transformer/model"

**Comment by MCLYang** [comment]
Close the thread. Please be aware about the version of bidict
